import type { Metadata } from "next";
import { Jaldi } from "next/font/google";
import "./globals.css";
import Layout from "../../components/layouts/article"
const inter = Jaldi({ subsets: ['devanagari'] , weight : ['400']});

export const metadata: Metadata = {
  title: "My portfolio",
  description: "Generated by me",
};

function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <Layout>
          {children}
      </Layout>
      {/* <body className={inter.className}>{children}</body> */}
    </html>
  );
}
export default RootLayout
