import type { Metadata } from "next";
import { Jaldi } from "next/font/google";
import "./globals.css";
import { Providers } from './providers'
// const inter = Jaldi({ subsets: ['devanagari'] , weight : ['400']});

export const metadata: Metadata = {
  title: "My portfolio",
  description: "Generated by me",
};

function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
export default RootLayout
